feat: Add i18n support
MoominBot/MoominBot pull request #16
Opened 2021-11-29 08:00 UTC by TheLearneer

TBD

2021-11-29 08:31 UTC, DevAndromeda requested changes

2021-11-29 08:31 UTC, DevAndromeda commented on src/utils/i18n.ts
> +const preloadData = readdirSync(join(__dirname(import.meta.url), "../locales")).filter((fileName) => {
why not promise here?

2021-11-29 08:44 UTC, TheLearneer commented on src/utils/i18n.ts
> +const preloadData = readdirSync(join(__dirname(import.meta.url), "../locales")).filter((fileName) => {
Will update

2021-11-30 16:20 UTC, DevAndromeda approved these changes

2021-12-18 05:24 UTC, TheLearneer commented
Opening new PR. This is way behind and is hard to resolve the conflicts

2021-12-18 05:24 UTC, closed without merging