feat: add some nepali commands
MoominBot/MoominBot pull request #56
Opened 2021-12-08 11:42 UTC by thenishantsapkota

2021-12-10 18:08 UTC, DevAndromeda commented on src/commands/General/CovidCommand.ts
> +                    name: "Today's Cases",
`name: "Cases Today",`

2021-12-10 18:08 UTC, DevAndromeda commented on src/commands/General/CovidCommand.ts
> +                    name: "Today's Deaths",
`name: "Deaths Today",`

2021-12-10 18:09 UTC, DevAndromeda requested changes

2021-12-10 18:09 UTC, DevAndromeda commented on src/commands/General/CovidCommand.ts
> +interface APIResponse{
```ts
interface APIResponse{
    country: string;
    cases: number;
    todayCases: number;
    deaths: number;
    todayDeaths: number;
    recovered: number;
    active: number;
    critical: number;
    totalTests: number;
}
```

2022-07-26 14:37 UTC, TheLearneer approved these changes
LGTM

2022-07-26 15:07 UTC, merged