feat(ModLog): add case and logs
MoominBot/MoominBot pull request #69
Opened 2021-12-17 09:26 UTC by DevAndromeda

this pr adds mod log and case system

2021-12-18 06:35 UTC, TheLearneer commented on src/commands/Moderation/BanCommand.ts
> +            return await interaction.followUp({ content: "No mod log channel found for this server" });
We don't want the users to compulsorily have mod logs enabled, do we?

The users should be able to ban member without having the modLog enabled.

2021-12-18 06:38 UTC, TheLearneer commented on src/commands/Moderation/CaseCommand.ts
> +        if (!server || !server.modlog || !interaction.guild?.channels.cache.has(server.modlog)) {
Since we have mod logs saved in the DB, we don't need modlog channel, do we?

2021-12-18 06:39 UTC, TheLearneer commented on src/commands/Moderation/KickCommand.ts
> +        if (!server || !server.modlog || !interaction.guild?.channels.cache.has(server.modlog)) {
Same as ban command

2021-12-18 06:40 UTC, TheLearneer commented on src/commands/Moderation/SoftBanCommand.ts
> +        if (!server || !server.modlog || !interaction.guild?.channels.cache.has(server.modlog)) {
Again, not sure if we want to force having the modLog channel

2021-12-18 06:43 UTC, TheLearneer requested changes
Few things seems to be blocking the commands if modLog channel is not setup, we might need to address that?

2021-12-18 11:09 UTC, DevAndromeda commented
> Few things seems to be blocking the commands if modLog channel is not setup, we might need to address that?

Mod log channel basically toggles moderation commands. If a server wants to disable moderation commands, they can simply remove the mod log channel. Whereas if they need moderation commands, they have to enable the mod log channel via `/config modlog <channel>`

2021-12-19 04:43 UTC, TheLearneer approved these changes

2021-12-21 11:07 UTC, merged